// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbrgdxzbluzpsgsrhtst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFicmdkeHpibHV6cHNnc3JodHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjkzMjMsImV4cCI6MjA2OTgwNTMyM30.a9G6XELj9RKIG2z7j0Rv5ZanZ-COs-zn0KcNecDM3_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});